### ISSUE TITLE
how to clear all subscriptions?

### ISSUE THREAD

**Issue by Zakhar88** [pisces/InstagramSDK#7]
Could you please show example how to clear all subscriptions?

**Comment by pisces** [comment]
What do you mean "subscriptions"?

**Comment by pisces** [comment]
Ah.. I see that mean. Sorry, skipped that implementing.
Today I'll add the api path for subscriptions to InstagramSDK v1.0.2 branch.

**Comment by Zakhar88** [comment]
I read that there is opportunity to clear all subscriptions by passing "object=all", but at this moment I can't even login through your example app:  error 400 "you must include a valid client_id, response_type, and redirect_uri parameters" (

**Comment by pisces** [comment]
You must join to instagram developer page. And register a new client.
Then you will get client id, client secret and others.
Here url -> https://www.instagram.com/developer/clients/manage/

Put your values to below code.

``` objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [[InstagramAppCenter defaultCenter] setUpWithClientId:@"clientId"
                                                     clientSecret:@"clientSecret"
                                                      redirectURL:@"redirectURL"];
    return YES;
}
```

**Comment by pisces** [comment]
1.0.2 branch published.
That version contains path for subscriptions.
Good luck!

``` objective-c

// Subscription list
[[InstagramAppCenter defaultCenter] IGApiPathSubscriptions param:nil completion:^(id result, NSError *error) {
     NSLog(@"result, error -> %@, %@", result, error);
}];

// Delete all subscriptions
[[InstagramAppCenter defaultCenter] IGApiPathSubscriptionsDel param:@{@"object": @"all"} completion:^(id result, NSError *error) {
     NSLog(@"result, error -> %@, %@", result, error);
}];

// Delete a subscription
[[InstagramAppCenter defaultCenter] IGApiPathSubscriptionsDel param:@{@"id": (1)} completion:^(id result, NSError *error) {
     NSLog(@"result, error -> %@, %@", result, error);
}];
```
